
package vistas;

import controlo.ControloCriarDispositivo;
import controlo.ControloCriarDivisao;
import controlo.LigacaoBD;
import controlo.ComboItem;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloCriarDivisao;
import modelo.ModeloTabela;

/**
 *
 * @author Celina
 */
public class FormCriaDivisao extends javax.swing.JFrame {
    
    ModeloCriarDivisao mod = new ModeloCriarDivisao();
    ControloCriarDivisao controlo = new ControloCriarDivisao();
    LigacaoBD liga = new LigacaoBD();
    int flag = 0;
    
  
    public FormCriaDivisao() {
        initComponents();
        preencherDivisao();
        //preencherTabela("select * from division order by id_divisao");
    }
    
    public void preencherDivisao(){
        
        liga.ligarBD();
        liga.executaSql("select * from division order by name");
        jComboBoxDispositivo.removeAllItems();
        
        try {
            liga.rs.first();
            
            do{
                jComboBoxDispositivo.addItem(liga.rs.getString("name"));
                //jComboBoxDispositivo.add(
                //        new ComboItem(liga.rs.getInt("id"), liga.rs.getString("name"))
                //);
            }while(liga.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"erro aoa preencher lista dos dispositivos"+ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldIDdivisao = new javax.swing.JTextField();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonGravar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelNomeDivisao = new javax.swing.JLabel();
        jTextFieldNomeDivisao = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("criar Divisao");
        getContentPane().setLayout(null);

        jLabelID.setText("ID");
        getContentPane().add(jLabelID);
        jLabelID.setBounds(20, 60, 37, 23);

        jTextFieldIDdivisao.setEnabled(false);
        getContentPane().add(jTextFieldIDdivisao);
        jTextFieldIDdivisao.setBounds(50, 60, 45, 20);
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(200, 60, 160, 20);

        jButtonPesquisar.setText("pesquisar");
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(380, 60, 79, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 270, 180, 92);

        jButtonGravar.setText("gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGravar);
        jButtonGravar.setBounds(500, 170, 80, 23);

        jButtonAlterar.setText("alterar");
        getContentPane().add(jButtonAlterar);
        jButtonAlterar.setBounds(500, 230, 80, 23);

        jButtonEliminar.setText("eliminar");
        getContentPane().add(jButtonEliminar);
        jButtonEliminar.setBounds(500, 270, 80, 23);

        jButtonSair.setText("sair");
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(500, 310, 80, 23);

        jLabelNomeDivisao.setText("nome");
        getContentPane().add(jLabelNomeDivisao);
        jLabelNomeDivisao.setBounds(10, 210, 48, 25);

        jTextFieldNomeDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeDivisaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeDivisao);
        jTextFieldNomeDivisao.setBounds(70, 210, 128, 20);

        jButtonNovo.setText("novo");
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(500, 140, 57, 23);

        jButtonCancelar.setText("cancelar");
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(500, 200, 73, 23);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 90, 452, 92);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 270, 200, 92);

        setSize(new java.awt.Dimension(616, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeDivisaoActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        
        //para não gravar dados em branco
        if(jTextFieldNomeDivisao.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"digite o nome");
            jTextFieldNomeDivisao.requestFocus();
        }else 
            
        if(flag == 1){
        mod.setNomeDivisao(jTextFieldNomeDivisao.getText());
        mod.setNomeDispositivo((String)jComboBoxDispositivo.getSelectedItem());
        
        //chama o metodo para gravaros dados
        controlo.gravar(mod);
        
        //limpa os campos
        jTextFieldIDdivisao.setText("");
        jTextFieldNomeDivisao.setText("");
        jTextFieldPesquisar.setText("");
        //muda estado dos campos e botoes
        jComboBoxDispositivo.setEnabled(false);
        jButtonGravar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
        // atualiza a tabela
        preencherTabela("select * from divisao order by id_divisao");
        
        
        }else{
             mod.setIdDivisao(Integer.parseInt(jTextFieldIDdivisao.getText()));
             mod.setNomeDivisao(jTextFieldNomeDivisao.getText());
             mod.setNomeDispositivo((String)jComboBoxDispositivo.getSelectedItem());
            
             //chama o metodo para alterar os dados
             controlo.alterar(mod);
         
             //limpa os campos
            jTextFieldDivisao.setText("");
            jTextFieldNomeDivisao.setText("");
            jTextFieldPesquisar.setText("");
            
            //muda estado dos campos e botoes
            jComboBoxDispositivo.setEnabled(false);
            jButtonGravar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            
            //atualiza a tabela
            preencherTabela("select * from dispositivo order by id_dispositivo");
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    
    //metodo para criar a tabela
    public void preencherTabela(String sql){
   
    ArrayList dados = new ArrayList();

    String[] colunas = new String[]{"id","dispositivo","divisao"};
    liga.ligarBD();
    liga.executaSql(sql);
    
   // liga.executaSql("select * from divisao inner join dispositivo on"
             //       + "divisao.id_dispositivo = dispositivo.id_dispositivo");

  
                     
   try{
       liga.rs.first();  //vamos buscar o primeiro resultado da pesquisa
       do{                 //enquanto houver dados
//            
              dados.add(new Object[]{ liga.rs.getInt("id_dispositivo"),liga.rs.getString("nome_dispositivo"), liga.rs.getString("nome_divisao")});     
        }while (liga.rs.next());    //vai percorrendo as posicoes
    }catch(SQLException ex){
      JOptionPane.showMessageDialog(null,"procure outra dispositivo"+ex);
    }


 
  ModeloTabela modTab = new ModeloTabela(dados, colunas);
  
    
    /*jTableDispositivo.setModel(modTab);
    jTableDispositivo.getColumnModel().getColumn(0).setPreferredWidth(127); //nome
    jTableDispositivo.getColumnModel().getColumn(0).setResizable(false); //nome
    jTableDispositivo.getColumnModel().getColumn(1).setPreferredWidth(153);
    jTableDispositivo.getColumnModel().getColumn(1).setResizable(false);
    jTableDispositivo.getColumnModel().getColumn(2).setPreferredWidth(153);
    jTableDispositivo.getColumnModel().getColumn(2).setResizable(false);
    //jTableDivisao.getColumnModel().getColumn(3).setPreferredWidth(80);
    //jTableDivisao.getColumnModel().getColumn(3).setResizable(false);
    jTableDispositivo.getTableHeader().setReorderingAllowed(false);
    jTableDispositivo.setAutoResizeMode(jTableDispositivo.AUTO_RESIZE_OFF);
    jTableDispositivo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//seleciona um dado de cada vez
*/
    liga.desligarBD();
    
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCriaDivisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCriaDivisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCriaDivisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCriaDivisao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCriaDivisao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNomeDivisao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextFieldIDdivisao;
    private javax.swing.JTextField jTextFieldNomeDivisao;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
